parameters:
    cache_tool.class: CacheTool\CacheTool
    cache_tool.adapter.cli.class: CacheTool\Adapter\Cli
    cache_tool.adapter.fastcgi.class: CacheTool\Adapter\FastCGI
    cache_tool.proxy.php.class: CacheTool\Proxy\PhpProxy
    cache_tool.proxy.apc.class: CacheTool\Proxy\ApcProxy
    cache_tool.proxy.opcache.class: CacheTool\Proxy\OpcacheProxy

services:
    cache_tool:
        class: %cache_tool.class%
        arguments: [@cache_tool.default_adapter]
        calls:
            - [addProxy, [@cache_tool.proxy.php]]
            - [addProxy, [@cache_tool.proxy.apc]]
            - [addProxy, [@cache_tool.proxy.opcache]]

    # Adapters

    cache_tool.adapter.cli:
        class: %cache_tool.adapter.cli.class%

    cache_tool.adapter.fastcgi:
        class: %cache_tool.adapter.fastcgi.class%
        arguments: [%cache_tool.adapter.fastcgi.connection%]

    # Proxies

    cache_tool.proxy.php:
        class: %cache_tool.proxy.php.class%

    cache_tool.proxy.apc:
        class: %cache_tool.proxy.apc.class%

    cache_tool.proxy.opcache:
        class: %cache_tool.proxy.opcache.class%
